#pragma once

//Screen
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 480
#define HEIGHTBOARD 50
#define MAX_WIDTH_LV1 1536

//map
#define TILE_MAP_SIZE 32

//Simon
#define SIMON_ATTACT_TIME 450

//Trạng thái di chuyển cùa simon
#define SIMON_STATE_IDLE				0
#define SIMON_STATE_WALKING_RIGHT		1
#define SIMON_STATE_WALKING_LEFT		2
#define SIMON_STATE_JUMP				3
#define SIMON_STATE_DIE					4
#define SIMON_STATE_SIT					5
#define SIMON_STATE_ATTACK				6
#define SIMON_STATE_ATTACK_WITH_SUB		7
#define SIMON_STATE_LEVEL_UP			8
#define SIMON_STATE_AUTO_WALK			9
#define SIMON_STATE_ATTACKED			10
#define SIMON_STATE_SIT_AFTER_FALL		11
#define SIMON_STATE_INVISIBLE			12
#define SIMON_STATE_UP_STAIR			13
#define SIMON_STATE_DOWN_STAIR			14
#define SIMON_STATE_IDLE_STAIR			15
#define SIMON_STATE_WALK				16

//animation của simon
#define SIMON_ANI_IDLE						0
#define SIMON_ANI_WALKING					1
#define SIMON_ANI_JUMPING					2
#define SIMON_ANI_SITTING					3
#define SIMON_ANI_STANDING_ATTACKING 		4
#define SIMON_ANI_SITTING_ATTACKING			5
#define SIMON_ANI_EATTING					6
#define SIMON_ANI_GO_UP 					7
#define SIMON_ANI_GO_DOWN					8
#define SIMON_ANI_HURT						9
#define SIMON_ANI_IDLE_UP					10
#define SIMON_ANI_IDLE_DOWN					11
#define SIMON_ANI_DIE						12


//Kích cờ simon
#define SIMON_BBOX_WIDTH			32
#define SIMON_BBOX_HEIGHT			64
#define SIMON_PADDING_ATTACT		16

#define SIMON_SIT_BBOX_WIDTH		32
#define SIMON_SIT_BBOX_HEIGHT		48
#define SIMON_PADDING_ANI			15
//tốc độ simon
#define SIMON_WALKING_SPEED			0.12f 
#define SIMON_JUMP_SPEED_Y			0.34f
#define SIMON_JUMP_GRAVITY			0.001f
#define SIMON_JUMP_DEFLECT_SPEED	0.02f
#define SIMON_GRAVITY				0.005f
#define SIMON_DIE_DEFLECT_SPEED		0.5f

//Thời gian simon
#define SIMON_UNTOUCHABLE_TIME		3000
#define SIMON_TIME_JUMPPING_SIT		400
//Whip
#define WHIP_BBOX_WIDGHT			80
#define WHIP_BBOX_HEIGHT			15

//Torch
#define TORCH_BBOX_WIDGHT			 32
#define TORCH_BBOX_HEIGHT			 64

//items
#define ITEM_GRAVITY				0.002f
#define HEART_BBOX_WIDTH			16
#define HEART_BBOX_HEIGHT			16

#define WHIPITEM_BBOX_WIDTH			32
#define WHIPITEM_BBOX_HEIGHT		32

#define MONEY_BBOX_WIDTH			30
#define MONEY_BBOX_HEIGHT			30

#define KNIFE_BBOX_WIDTH			32
#define KNIFE_BBOX_HEIGHT			18

enum ItemType
{
	HEART = 1,
	WHIP = 2,
	MONEY = 3,
	KNIFE = 4
};

//effect
#define TIME_EFFECT					450